### ISSUE TITLE
Thank you for the great work done, Russell.

### ISSUE THREAD

**Issue by kenghweeng** [RussellDash332/EXPOSE-DSA#3]
Good job on the introduction to DSA, very happy to connect with you here :)

**Comment by RussellDash332** [comment]
I have to thank @wilsonwid actually

**Comment by kenghweeng** [comment]
That's great to know, thank you @wilsonwid for the fantastic work done. Maybe including a 3D plot for the wowz might be great: https://plotly.com/python/3d-scatter-plots/

**Comment by RussellDash332** [comment]
Thanks for closing the issue! We will definitely make the 3D plot next time.

**Comment by wilsonwid** [comment]
> That's great to know, thank you @wilsonwid for the fantastic work done. Maybe including a 3D plot for the wowz might be great: https://plotly.com/python/3d-scatter-plots/

Thank you and our (my) pleasure @kenghweeng, will implement the 3D plot next time.
